### ISSUE TITLE
Pact checklist

### ISSUE THREAD

**Issue by sldblog** [ministryofjustice/hmpps-interventions-service#22]
Copied from https://github.com/pact-foundation/pact_broker/wiki/Set-up-checklist

----

This is a high level check list of things that need to be done when setting up an integration to be tested with Pact using the Pact Broker. As there are many Pact implementations in different languages, you will need to consult the documentation for your language to find out how to implement each step. See [The steps to reaching Pact Nirvana](https://docs.google.com/document/d/e/2PACX-1vRf1kSDccImNipOOm1G-bjcSs-ifbZjf1v54K-dIcq8BLKeFPAAm_bf_p71UKqkRMIx30QWWL-kN8TI/pub) for an in depth explanation of the purpose of each step.

## Basic

This will get you to the stage where your consumer and provider have a pact that is generated and verified automatically, with a set up that allows you to introduce changes without breaking the provider build.

### Anyone

See https://github.com/ministryofjustice/hmpps-interventions-ui/issues/38

### Consumer team

See https://github.com/ministryofjustice/hmpps-interventions-ui/issues/38

### Provider team

* [x] Add a pact verification test to the provider build
* [x] Configure the verification test to verify the pacts with the tag `master` (or whatever the "main line" of development is called)
* [x] Configure the pact verification task to publish verification results only when run on the CI.
* [x] Create a separate CI job that just does the pact verification/results publishing steps. It should accept the URL of the changed pact as a parameter (see the [webhooks][webhooks] page for more information on this).
* [x] Create a webhook that triggers the pact verification CI job when a pact changes, and use the webhook template parameters to pass the URL of the changed pact into the CI job (see the [webhooks][webhooks] page for more information on this).

## Advanced

Skipping this part.

[can-i-deploy]: https://github.com/pact-foundation/pact_broker/wiki/can-i-deploy
[webhooks]: https://github.com/pact-foundation/pact_broker/wiki/Webhooks
[tag]: https://github.com/pact-foundation/pact_broker-client#create-version-tag

**Comment by sldblog** [comment]
Webhook added in https://github.com/ministryofjustice/hmpps-pact-broker/commit/27777b3df634c86f17de4ef394b36f418c60a11f

Separate CI job added in #65
